CREATE TABLE `civicrm_property` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `vge_id` int(11) DEFAULT NULL,
  `complex_id` varchar(45) DEFAULT NULL,
  `subcomplex` varchar(45) DEFAULT NULL,
  `vge_street_name` varchar(128) DEFAULT NULL,
  `vge_street_number` int(11) DEFAULT NULL,
  `vge_street_unit` varchar(45) DEFAULT NULL,
  `vge_postal_code` varchar(45) DEFAULT NULL,
  `vge_city` varchar(75) DEFAULT NULL,
  `vge_country_id` int(11) DEFAULT NULL,
  `vge_address_id` int(11) DEFAULT NULL,
  `epa_label` varchar(45) DEFAULT NULL,
  `epa_pre` varchar(45) DEFAULT NULL,
  `city_region` varchar(128) DEFAULT NULL,
  `block` varchar(128) DEFAULT NULL,
  `vge_type_id` int(11) DEFAULT NULL,
  `strategy_label` varchar(45) DEFAULT NULL,
  `strategy_b_pnts` int(11) DEFAULT NULL,
  `strategy_c_pnts` int(11) DEFAULT NULL,
  `number_rooms` int(11) DEFAULT NULL,
  `outside_code` varchar(45) DEFAULT NULL,
  `stairs` tinyint(4) DEFAULT NULL,
  `build_year` tinyint(4) DEFAULT NULL,
  `square_mtrs` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `vge_id` (`vge_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE = utf8_general_ci;
